//CREATE TABLE CARS (
//        id int NOT NULL  PRIMARY KEY AUTO_INCREMENT,name varchar(50) NOT NULL,make varchar(50) NOT NULL,
//        year varchar(50) NOT NULL,
//        color varchar(20)
//        );

//INSERT INTO CARS(NAME,MAKE,YEAR,COLOR) VALUES ('TOYOTA','CAMRY','2011','BLACK');
//        INSERT INTO CARS(NAME,MAKE,YEAR,COLOR) VALUES ('TOYOTA','SIENNA','2015','RED');
//                INSERT INTO CARS(NAME,MAKE,YEAR,COLOR) VALUES ('HONDA','WAGON','2015','RED');
//                INSERT INTO CARS(NAME,MAKE,YEAR,COLOR) VALUES ('BMW','SEDAN','2020','BLUE');
//                INSERT INTO CARS(NAME,MAKE,YEAR,COLOR) VALUES ('DODGE','HATCHBACK','2018','YELLOW');


